import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#eaf7ff',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        overflow: 'hidden',
    },
    card: {
        width: '100%',
        maxWidth: 430,
        backgroundColor: 'rgba(255,255,255,0.7)',
        borderRadius: 30,
        padding: 22,
        alignItems: 'center',
        shadowColor: '#0f4c81',
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.14,
        shadowRadius: 20,
        elevation: 8,
        zIndex: 2,
    },
    title: {
        fontSize: 30,
        fontWeight: '700',
        color: '#0d5d8f',
        marginBottom: 18,
        letterSpacing: 0.5,
    },
    bottleWrap: {
        marginBottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    bottleCap: {
        width: 44,
        height: 18,
        backgroundColor: '#d9ebff',
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        borderWidth: 1,
        borderColor: '#bcd7f7',
        marginBottom: 2,
    },
    bottleNeck: {
        width: 72,
        height: 18,
        backgroundColor: '#edf6ff',
        borderWidth: 1,
        borderColor: '#cfe6ff',
        borderRadius: 10,
    },
    bottleBody: {
        width: 118,
        height: 178,
        borderRadius: 28,
        backgroundColor: 'rgba(255,255,255,0.72)',
        borderWidth: 2,
        borderColor: '#cfe6ff',
        overflow: 'hidden',
        justifyContent: 'flex-end',
        marginTop: -2,
        shadowColor: '#59b9f5',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 12,
    },
    bottleFill: {
        width: '100%',
        backgroundColor: '#69d3ff',
        borderRadius: 24,
        overflow: 'hidden',
        minHeight: 0,
    },
    waterWave: {
        width: '130%',
        height: 20,
        backgroundColor: 'rgba(255,255,255,0.28)',
        borderRadius: 100,
        marginTop: -6,
    },
    levelText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#2d7eb8',
        marginTop: 8,
        marginBottom: 16,
        letterSpacing: 0.4,
    },
    resultado: {
        fontSize: 18,
        color: '#0d3d59',
        marginTop: 14,
        textAlign: 'center',
    },
    progressBarBackground: {
        width: '100%',
        height: 14,
        backgroundColor: '#dfeefc',
        borderRadius: 20,
        overflow: 'hidden',
        marginTop: 18,
        marginBottom: 12,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#4bb7ff',
        borderRadius: 20,
    },
    actionsRow: {
        width: '100%',
        marginTop: 8,
    },
    wave: {
        position: 'absolute',
        width: 520,
        height: 180,
        borderRadius: 120,
        backgroundColor: 'rgba(124, 214, 255, 0.2)',
        bottom: -24,
        left: -40,
        zIndex: 1,
    },
    waveOne: {
        opacity: 0.8,
    },
    waveTwo: {
        bottom: -42,
        left: -80,
        opacity: 0.95,
    },
});

export default styles;